# Generated by Django 3.2.16 on 2022-11-17 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surfclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('Beginner Surf Lesson', 'Beginner Surf Lesson'), ('Intermediate Surf Lesson', 'Intermediate Surf Lesson'), ('Surf Coaching', 'Surf Coaching'), ('Kids Camp', 'Kids Camp')], default='Beginner Surf Lesson', max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('18:00', '18:00')], default='10:00', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
