# Generated by Django 3.2.16 on 2022-11-18 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfclub', '0002_auto_20221117_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('18:00', '18:00')], default='10:00', max_length=10)),
                ('options', models.CharField(choices=[('Beginner Surf Lesson', 'Beginner Surf Lesson'), ('Intermediate Surf Lesson', 'Intermediate Surf Lesson'), ('Surf Coaching', 'Surf Coaching'), ('Kids Camp', 'Kids Camp')], default='Beginner Surf Lesson', max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
