# Generated by Django 3.2.16 on 2022-11-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfclub', '0003_bookingcustomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingcustomer',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
